name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz --exclude '.git' ./app/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

      - name: Run deploy script on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/app &&
            pip install -r requirements.txt &&
            fuser -k 5000/tcp || true &&
            fuser -k 5001/tcp || true &&
            PORT=5000 nohup python3 app.py > /dev/null 2>&1 &
            PORT=5001 nohup python3 app.py > /dev/null 2>&1 &
          "
